### 下载 agent 二进制程序
GET {{host}}/api/agent-release?id=6909eae156d2cd88047aaeb2

### 上传文件
POST {{host}}/api/agent-release
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="aegis-agent_windows-arm64_v25.11.04-032143.exe"

< aegis-agent_windows-arm64_v25.11.04-032143.exe
--WebAppBoundary--


### 获取任务列表
GET https://{{host}}/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/tasks
Cache-Control: no-cache

### 下发任务
POST https://{{host}}/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/task/exec
Content-Type: application/json

{
  "name": "http-server",
  "code": "import console from 'console'\nimport time from 'time'\nimport url from 'net/url'\nimport http from 'net/http'\nimport httputil from 'net/http/httputil'\nconst target = url.parse('https://mirrors.zju.edu.cn/')\nconst proxy = httputil.newSingleHostReverseProxy(target)\nlet count = 0\nconst mux = http.newServeMux()\nmux.handleFunc('/', (w, r) => {\nw.header().set('Content-Type', 'text/html')\nw.write('<h1>欢迎访问：${r.url.path}</h1>')\ncount++\nconsole.log(`${r.remoteAddr}: ${r.url.path} ${r.url.rawQuery}`)\n})\nconst opt = {addr: '0.0.0.0:8888', handler: mux, readTimeout: time.minute, readHeaderTimeout: 5 * time.second}\nconst handle = http.serve(opt)\nhandle.wait()"
}

### 结束任务
DELETE https://{{host}}/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/task/kill?pid=1


### 测试 SNI
GET https://lo.rust.wang:8443/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/tasks

### 删除二进制
DELETE wss://47.116.221.17:8443/api/reverse/broker/6914798742be64881538d823/api/reverse/690863f38248c531a77bcce3/api/task/attach?pid=1
// 68f7502cc628b9e207f564d6