### 下载 agent 二进制程序
GET {{host}}/api/agent-release?id=6909eae156d2cd88047aaeb2

### 上传文件
POST {{host}}/api/agent-release
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="aegis-agent_windows-arm64_v25.11.04-032143.exe"

< aegis-agent_windows-arm64_v25.11.04-032143.exe
--WebAppBoundary--


### 获取任务列表
GET {{host}}/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/tasks

### 下发任务
POST {{host}}/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/task/exec
Content-Type: application/json

{
  "name": "http-server",
  "code": "import time from 'time'\nimport url from 'net/url'\nimport http from 'net/http'\nimport httputil from 'net/http/httputil'\nconst target = url.parse('https://mirrors.zju.edu.cn/')\nconst proxy = httputil.newSingleHostReverseProxy(target)\nconst mux = http.newServeMux()\nmux.handleFunc('/', (w, r) => {\nw.header().set('Content-Type', 'text/html')\nw.write('<h1>HELLO</h1>')\n})\nconst opt = {\naddr: '0.0.0.0:8888', \nhandler: proxy,\n//handler: mux, \nreadTimeout: time.minute, \nreadHeaderTimeout: 5 * time.second,\n}\nconst handle = http.serve(opt)\nhandle.wait()"
}

### 结束任务
DELETE {{host}}/api/reverse/broker/{{brokerId}}/api/reverse/{{agentId}}/api/task/kill?pid=2
