### 创建 broker 节点
POST {{host}}/api/broker
Content-Type: application/json

{
  "name": "本地测试",
  "exposes": [
    "172.31.61.168:9443"
  ],
  "config": {
    "server": {
      "addr": "0.0.0.0:9443"
    }
  }
}

### 上传 broker 二进制
POST {{host}}/api/broker-release
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="changelog"
Content-Type: text/plain

测试发布版本
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="aegis-broker_linux-arm64_v25.11.8-111641"
Content-Type: application/json

< aegis-broker_linux-arm64_v25.11.8-111641
--WebAppBoundary--
