// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/xmx/aegis-server/datalayer/model"
)

func newConfigLogger(db *gorm.DB, opts ...gen.DOOption) configLogger {
	_configLogger := configLogger{}

	_configLogger.configLoggerDo.UseDB(db, opts...)
	_configLogger.configLoggerDo.UseModel(&model.ConfigLogger{})

	tableName := _configLogger.configLoggerDo.TableName()
	_configLogger.ALL = field.NewAsterisk(tableName)
	_configLogger.ID = field.NewInt64(tableName, "id")
	_configLogger.Enabled = field.NewBool(tableName, "enabled")
	_configLogger.Level = field.NewString(tableName, "level")
	_configLogger.Terminal = field.NewBool(tableName, "terminal")
	_configLogger.Filename = field.NewString(tableName, "filename")
	_configLogger.MaxAge = field.NewInt64(tableName, "max_age")
	_configLogger.MaxBackup = field.NewInt64(tableName, "max_backup")
	_configLogger.Localtime = field.NewBool(tableName, "localtime")
	_configLogger.Compress = field.NewBool(tableName, "compress")
	_configLogger.UpdatedAt = field.NewTime(tableName, "updated_at")
	_configLogger.CreatedAt = field.NewTime(tableName, "created_at")

	_configLogger.fillFieldMap()

	return _configLogger
}

type configLogger struct {
	configLoggerDo configLoggerDo

	ALL       field.Asterisk
	ID        field.Int64
	Enabled   field.Bool
	Level     field.String
	Terminal  field.Bool
	Filename  field.String
	MaxAge    field.Int64
	MaxBackup field.Int64
	Localtime field.Bool
	Compress  field.Bool
	UpdatedAt field.Time
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c configLogger) Table(newTableName string) *configLogger {
	c.configLoggerDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c configLogger) As(alias string) *configLogger {
	c.configLoggerDo.DO = *(c.configLoggerDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *configLogger) updateTableName(table string) *configLogger {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Enabled = field.NewBool(table, "enabled")
	c.Level = field.NewString(table, "level")
	c.Terminal = field.NewBool(table, "terminal")
	c.Filename = field.NewString(table, "filename")
	c.MaxAge = field.NewInt64(table, "max_age")
	c.MaxBackup = field.NewInt64(table, "max_backup")
	c.Localtime = field.NewBool(table, "localtime")
	c.Compress = field.NewBool(table, "compress")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *configLogger) WithContext(ctx context.Context) *configLoggerDo {
	return c.configLoggerDo.WithContext(ctx)
}

func (c configLogger) TableName() string { return c.configLoggerDo.TableName() }

func (c configLogger) Alias() string { return c.configLoggerDo.Alias() }

func (c configLogger) Columns(cols ...field.Expr) gen.Columns {
	return c.configLoggerDo.Columns(cols...)
}

func (c *configLogger) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *configLogger) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["enabled"] = c.Enabled
	c.fieldMap["level"] = c.Level
	c.fieldMap["terminal"] = c.Terminal
	c.fieldMap["filename"] = c.Filename
	c.fieldMap["max_age"] = c.MaxAge
	c.fieldMap["max_backup"] = c.MaxBackup
	c.fieldMap["localtime"] = c.Localtime
	c.fieldMap["compress"] = c.Compress
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c configLogger) clone(db *gorm.DB) configLogger {
	c.configLoggerDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c configLogger) replaceDB(db *gorm.DB) configLogger {
	c.configLoggerDo.ReplaceDB(db)
	return c
}

type configLoggerDo struct{ gen.DO }

func (c configLoggerDo) Debug() *configLoggerDo {
	return c.withDO(c.DO.Debug())
}

func (c configLoggerDo) WithContext(ctx context.Context) *configLoggerDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c configLoggerDo) ReadDB() *configLoggerDo {
	return c.Clauses(dbresolver.Read)
}

func (c configLoggerDo) WriteDB() *configLoggerDo {
	return c.Clauses(dbresolver.Write)
}

func (c configLoggerDo) Session(config *gorm.Session) *configLoggerDo {
	return c.withDO(c.DO.Session(config))
}

func (c configLoggerDo) Clauses(conds ...clause.Expression) *configLoggerDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c configLoggerDo) Returning(value interface{}, columns ...string) *configLoggerDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c configLoggerDo) Not(conds ...gen.Condition) *configLoggerDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c configLoggerDo) Or(conds ...gen.Condition) *configLoggerDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c configLoggerDo) Select(conds ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c configLoggerDo) Where(conds ...gen.Condition) *configLoggerDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c configLoggerDo) Order(conds ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c configLoggerDo) Distinct(cols ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c configLoggerDo) Omit(cols ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c configLoggerDo) Join(table schema.Tabler, on ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c configLoggerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c configLoggerDo) RightJoin(table schema.Tabler, on ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c configLoggerDo) Group(cols ...field.Expr) *configLoggerDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c configLoggerDo) Having(conds ...gen.Condition) *configLoggerDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c configLoggerDo) Limit(limit int) *configLoggerDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c configLoggerDo) Offset(offset int) *configLoggerDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c configLoggerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *configLoggerDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c configLoggerDo) Unscoped() *configLoggerDo {
	return c.withDO(c.DO.Unscoped())
}

func (c configLoggerDo) Create(values ...*model.ConfigLogger) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c configLoggerDo) CreateInBatches(values []*model.ConfigLogger, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c configLoggerDo) Save(values ...*model.ConfigLogger) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c configLoggerDo) First() (*model.ConfigLogger, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigLogger), nil
	}
}

func (c configLoggerDo) Take() (*model.ConfigLogger, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigLogger), nil
	}
}

func (c configLoggerDo) Last() (*model.ConfigLogger, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigLogger), nil
	}
}

func (c configLoggerDo) Find() ([]*model.ConfigLogger, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConfigLogger), err
}

func (c configLoggerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigLogger, err error) {
	buf := make([]*model.ConfigLogger, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c configLoggerDo) FindInBatches(result *[]*model.ConfigLogger, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c configLoggerDo) Attrs(attrs ...field.AssignExpr) *configLoggerDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c configLoggerDo) Assign(attrs ...field.AssignExpr) *configLoggerDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c configLoggerDo) Joins(fields ...field.RelationField) *configLoggerDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c configLoggerDo) Preload(fields ...field.RelationField) *configLoggerDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c configLoggerDo) FirstOrInit() (*model.ConfigLogger, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigLogger), nil
	}
}

func (c configLoggerDo) FirstOrCreate() (*model.ConfigLogger, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigLogger), nil
	}
}

func (c configLoggerDo) FindByPage(offset int, limit int) (result []*model.ConfigLogger, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c configLoggerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c configLoggerDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c configLoggerDo) Delete(models ...*model.ConfigLogger) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *configLoggerDo) withDO(do gen.Dao) *configLoggerDo {
	c.DO = *do.(*gen.DO)
	return c
}
