// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	ConfigCertificate *configCertificate
	GridChunk         *gridChunk
	GridFile          *gridFile
	Menu              *menu
	OAuthConfig       *oAuthConfig
	Oplog             *oplog
	Role              *role
	RoleMenu          *roleMenu
	User              *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ConfigCertificate = &Q.ConfigCertificate
	GridChunk = &Q.GridChunk
	GridFile = &Q.GridFile
	Menu = &Q.Menu
	OAuthConfig = &Q.OAuthConfig
	Oplog = &Q.Oplog
	Role = &Q.Role
	RoleMenu = &Q.RoleMenu
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		ConfigCertificate: newConfigCertificate(db, opts...),
		GridChunk:         newGridChunk(db, opts...),
		GridFile:          newGridFile(db, opts...),
		Menu:              newMenu(db, opts...),
		OAuthConfig:       newOAuthConfig(db, opts...),
		Oplog:             newOplog(db, opts...),
		Role:              newRole(db, opts...),
		RoleMenu:          newRoleMenu(db, opts...),
		User:              newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ConfigCertificate configCertificate
	GridChunk         gridChunk
	GridFile          gridFile
	Menu              menu
	OAuthConfig       oAuthConfig
	Oplog             oplog
	Role              role
	RoleMenu          roleMenu
	User              user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		ConfigCertificate: q.ConfigCertificate.clone(db),
		GridChunk:         q.GridChunk.clone(db),
		GridFile:          q.GridFile.clone(db),
		Menu:              q.Menu.clone(db),
		OAuthConfig:       q.OAuthConfig.clone(db),
		Oplog:             q.Oplog.clone(db),
		Role:              q.Role.clone(db),
		RoleMenu:          q.RoleMenu.clone(db),
		User:              q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		ConfigCertificate: q.ConfigCertificate.replaceDB(db),
		GridChunk:         q.GridChunk.replaceDB(db),
		GridFile:          q.GridFile.replaceDB(db),
		Menu:              q.Menu.replaceDB(db),
		OAuthConfig:       q.OAuthConfig.replaceDB(db),
		Oplog:             q.Oplog.replaceDB(db),
		Role:              q.Role.replaceDB(db),
		RoleMenu:          q.RoleMenu.replaceDB(db),
		User:              q.User.replaceDB(db),
	}
}

type queryCtx struct {
	ConfigCertificate *configCertificateDo
	GridChunk         *gridChunkDo
	GridFile          *gridFileDo
	Menu              *menuDo
	OAuthConfig       *oAuthConfigDo
	Oplog             *oplogDo
	Role              *roleDo
	RoleMenu          *roleMenuDo
	User              *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ConfigCertificate: q.ConfigCertificate.WithContext(ctx),
		GridChunk:         q.GridChunk.WithContext(ctx),
		GridFile:          q.GridFile.WithContext(ctx),
		Menu:              q.Menu.WithContext(ctx),
		OAuthConfig:       q.OAuthConfig.WithContext(ctx),
		Oplog:             q.Oplog.WithContext(ctx),
		Role:              q.Role.WithContext(ctx),
		RoleMenu:          q.RoleMenu.WithContext(ctx),
		User:              q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
