// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	ConfigCertificate *configCertificate
	ConfigServer      *configServer
	GridChunk         *gridChunk
	GridFile          *gridFile
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ConfigCertificate = &Q.ConfigCertificate
	ConfigServer = &Q.ConfigServer
	GridChunk = &Q.GridChunk
	GridFile = &Q.GridFile
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		ConfigCertificate: newConfigCertificate(db, opts...),
		ConfigServer:      newConfigServer(db, opts...),
		GridChunk:         newGridChunk(db, opts...),
		GridFile:          newGridFile(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ConfigCertificate configCertificate
	ConfigServer      configServer
	GridChunk         gridChunk
	GridFile          gridFile
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		ConfigCertificate: q.ConfigCertificate.clone(db),
		ConfigServer:      q.ConfigServer.clone(db),
		GridChunk:         q.GridChunk.clone(db),
		GridFile:          q.GridFile.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		ConfigCertificate: q.ConfigCertificate.replaceDB(db),
		ConfigServer:      q.ConfigServer.replaceDB(db),
		GridChunk:         q.GridChunk.replaceDB(db),
		GridFile:          q.GridFile.replaceDB(db),
	}
}

type queryCtx struct {
	ConfigCertificate *configCertificateDo
	ConfigServer      *configServerDo
	GridChunk         *gridChunkDo
	GridFile          *gridFileDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ConfigCertificate: q.ConfigCertificate.WithContext(ctx),
		ConfigServer:      q.ConfigServer.WithContext(ctx),
		GridChunk:         q.GridChunk.WithContext(ctx),
		GridFile:          q.GridFile.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
