package restapi

import (
	"context"
	"net"
	"net/http"
	"sync"
	"time"

	"github.com/labstack/echo/v5"
	"github.com/xmx/aegis-server/application/config"
	"github.com/xmx/aegis-server/application/errcode"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"go.mongodb.org/mongo-driver/v2/x/mongo/driver/connstring"
)

// OOBE 即 Out-of-Box Experience（开箱体验）。
//
// 当本软件首次安装时，通过网页图形化界面来引导用户初始化配置。
type OOBE struct {
	retch chan<- *config.Config // 配置参数初始化完毕后，通过 chan 通知主程序
	file  string                // 配置文件写入位置
	mutex sync.RWMutex
	done  bool
}

func NewOOBE(retch chan<- *config.Config, file string) *OOBE {
	return &OOBE{
		retch: retch,
		file:  file,
	}
}

func (ob *OOBE) RegisterRoute(r *echo.Group) error {
	r.GET("/oobe", ob.config)
	r.POST("/oobe", ob.setup)

	return nil
}

func (ob *OOBE) config(c *echo.Context) error {
	ob.mutex.RLock()
	done := ob.done
	ob.mutex.RUnlock()
	if done {
		return errcode.ErrOOBEFinished
	}

	ctx := c.Request().Context()
	val := ctx.Value(http.LocalAddrContextKey)
	var bind string
	if addr, _ := val.(net.Addr); addr != nil {
		str := addr.String()
		if _, port, _ := net.SplitHostPort(str); port != "" {
			host := net.IPv4zero.String()
			bind = net.JoinHostPort(host, port)
			c.Logger().DebugContext(ctx, "推荐监听地址", "address", bind)
		}
	}

	ret := &config.Config{}

	return c.JSON(http.StatusOK, ret)
}

//goland:noinspection GoUnhandledErrorResult
func (ob *OOBE) setup(c *echo.Context) error {
	req := new(config.Config)
	if err := c.Bind(req); err != nil {
		return err
	}
	parent := c.Request().Context()

	ob.mutex.Lock()
	defer ob.mutex.Unlock()
	if ob.done { // 程序已经初始化完毕，禁止再次初始化。
		return errcode.ErrOOBEFinished
	}

	// 检查监听地址是否可用（如果端口号一致要排除掉自身服务占用的情况）
	//{
	//	addr := srvc.Addr
	//	taddr, err := net.ResolveTCPAddr("tcp", addr)
	//	if err != nil {
	//		c.Errorf("%s 不是合法的监听地址：%s", addr, err)
	//		return err
	//	}
	//
	//	// var samePort bool
	//	var curport int
	//	val := parent.Value(http.LocalAddrContextKey)
	//	if neta, _ := val.(*net.TCPAddr); neta != nil {
	//		curport = neta.Port
	//	}
	//	if curport == taddr.Port {
	//		c.Infof("与初始化服务使用同样的端口：%d", curport)
	//	} else {
	//		ln, err1 := net.Listen("tcp", addr)
	//		if err1 != nil {
	//			c.Errorf("预检监听地址错误：%s", err1)
	//			return err1
	//		}
	//		_ = ln.Close()
	//	}
	//}

	// 数据库是否可用
	mongoURI := req.Database.URI
	mongoURL, err := connstring.ParseAndValidate(mongoURI)
	if err != nil {
		return err
	}
	dbname := mongoURL.Database
	if dbname == "" {
		return echo.ErrBadRequest
	}

	ctx, cancel := context.WithTimeout(parent, 10*time.Second)
	defer cancel()

	opt := options.Client().ApplyURI(mongoURI)
	cli, err := mongo.Connect(opt)
	if err != nil {
		return err
	}
	defer cli.Disconnect(ctx)
	if err = cli.Ping(ctx, nil); err != nil {
		return err
	}

	// 写入配置文件
	now := time.Now()
	stamp := now.Format(time.RFC3339)
	comment := "This file was generated by AEGIS OOBE on " + stamp
	if err = config.WriteFile(ob.file, req, comment); err != nil {
		return echo.ErrInternalServerError.Wrap(err)
	}

	ob.retch <- req
	ob.done = true // 标记初始化完毕

	return c.NoContent(http.StatusCreated)
}
